name: todo_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  get_storage: ^2.1.1
  get: ^4.6.6
  intl: 
  google_fonts: 
  date_picker_timeline: ^1.2.5
  flutter_local_notifications: ^17.0.0
  timezone: ^0.9.0
  sqflite: ^2.0.0+4
  flutter_svg: ^1.1.6
  flutter_staggered_animations: ^1.1.1
  flutter_colorpicker: ^1.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/profile.png
    - assets/